version: '3.8'

services:
  # FastAPI Application
  app:
    image: singhaditya4:evently-app
    container_name: evently-app
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - EVENTS_TABLE_NAME=${EVENTS_TABLE_NAME:-Evently-Table}
      - DEBUG=${DEBUG:-False}
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - evently-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: evently-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - evently-network

networks:
  evently-network:
    driver: bridge

volumes:
  nginx_logs:
